# Generated by Django 4.2.14 on 2024-08-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электричество'), ('hybrid', 'Гибрид')], max_length=10, verbose_name='Тип топлива')),
                ('transmission_type', models.CharField(choices=[('manual', 'Механическая'), ('automatic', 'Автоматическая'), ('cvt', 'Вариатор'), ('robot', 'Робот')], max_length=10, verbose_name='Тип КПП')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
